
# To use this file::
#  conda env create -f tt.yml
# or to install direction from the web
#  conda env create camsys/tt

name: tt

channels:
- conda-forge

dependencies:
- python=3.9
- pip

# Math
- numpy>=1.16
- pandas>=1.2
- scipy>=1.2
- numba
- autograd

# Networks
- networkx>=2.2

# YAML Processing
- yamllint>=1.11

# Data Storage and File Management
- pytables>=3.6
- h5py>=2.8.0
- hdf5>=1.10.2
- appdirs>=1.4.3

# Visualization
- matplotlib>=3.0.1
- seaborn>=0.9
- pydot
- graphviz>=2.38
- plotly>=4.14
- python-kaleido  # Plotly Static Image Export

# Mapping
- fiona>=1.7.11
- gdal>=2.2.4
- geopandas
- krb5>=1.16
- shapely>=1.6.4
- osmnx>=0.9
- contextily
- libiconv
- fontconfig
- folium

# User Interface
- ipywidgets>=7.2

# Parallel Processing
- joblib>=0.13.2
- cloudpickle>=0.6.1

# MS Excel Compatibility
- openpyxl>=2.4
- xlrd

# HTML Compatibility
- beautifulsoup4>=4.6
- jinja2>=2.9.6  # for pandas styler
- xmle
- html5lib

# Jupyter and IPython
- ipykernel>=5.1
- nb_conda>=2.2.1
- jupyterlab>=0.35.3
- notebook>=5.7.2
- nodejs

# Choice Modeling
- larch>=5.1

# Testing
- pytest>=4.0.1

- pip:
  - transportation_tutorials



# These may also be of interest for jupyter lab users:
#
# Avoid "JavaScript heap out of memory" errors during extension installation::
#   # (OS X/Linux)
#   export NODE_OPTIONS=--max-old-space-size=4096
#   # (Windows)
#   set NODE_OPTIONS=--max-old-space-size=4096
#
# jupyter labextension install @jupyterlab/toc --no-build
# jupyter labextension install @jupyter-widgets/jupyterlab-manager --no-build
# jupyter labextension install jupyterlab_bokeh --no-build
# jupyter labextension install @jupyterlab/plotly-extension --no-build
# jupyter labextension install @jupyterlab/geojson-extension --no-build
# jupyter labextension install @jupyterlab/mathjax3-extension --no-build
# jupyter labextension install plotlywidget --no-build
# jupyter lab build
#
